import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

type JsonRecord = Record<string, unknown> & {
  id: string;
  source_refs: string[];
};

type InterviewPerson = {
  name: string;
  role: string;
  department: string;
  email: string;
  source: string;
};

const normalizedDir = path.join(process.cwd(), "data", "normalized");

async function main() {
  const people = await readInterviewPeople();
  const entityRecords = [...seedEntityRecords(), ...personEntityRecords(people)];
  const factRecords = seedFactRecords();
  const causalRecords = seedCausalRecords();

  validateSourceRefs([...entityRecords, ...factRecords, ...causalRecords]);

  await mkdir(normalizedDir, { recursive: true });
  await writeJsonl("entities.jsonl", entityRecords);
  await writeJsonl("facts.jsonl", factRecords);
  await writeJsonl("causal_chains.jsonl", causalRecords);
  await writeFile(
    path.join(normalizedDir, "README.md"),
    [
      "# Normalized Knowledge Layer",
      "",
      "This directory is generated by `npm run normalize`.",
      "",
      "The generic assistant should prefer these records for entity, alias, relationship, freshness, conflict, and causality resolution, then use original files in `data/` as provenance and fallback evidence.",
      "",
      "Each JSONL record includes `source_refs` pointing to original records that back the normalized interpretation. Normalized files guide reasoning but should not be cited as user-facing sources.",
      "",
    ].join("\n"),
    "utf8",
  );

  console.log(`Wrote ${entityRecords.length} entities, ${factRecords.length} facts, ${causalRecords.length} causal chains.`);
}

function seedEntityRecords(): JsonRecord[] {
  return [
    {
      id: "entity.org.helixpay_brasil",
      type: "organization",
      canonical_name: "HelixPay Brasil",
      aliases: ["HPB", "Helix Brasil", "Brasil", "Brazil"],
      confidence: 0.98,
      source_refs: ["data/overview.md", "data/org-chart.md"],
    },
    {
      id: "entity.product.pos",
      type: "product",
      canonical_name: "HelixPay POS",
      aliases: ["POS", "card-reader terminal"],
      confidence: 0.96,
      source_refs: ["data/overview.md"],
    },
    {
      id: "entity.product.pos_self_service",
      type: "product",
      canonical_name: "HelixPay POS Self-Service",
      aliases: ["POS Self-Service", "Self-Serve", "POS SS", "kiosk product", "kiosk"],
      distinct_from: ["entity.product.pos"],
      confidence: 0.98,
      source_refs: ["data/overview.md", "data/interviews/product__pos_self_service/Vinod_Krishnan.md"],
    },
    {
      id: "entity.product.tap",
      type: "product",
      canonical_name: "HelixPay Tap",
      aliases: ["Tap", "tap-on-phone"],
      confidence: 0.96,
      source_refs: ["data/overview.md", "data/interviews/sales/joao_pereira.md", "data/interviews/engineering/Ahmad_Rashid.md"],
    },
    {
      id: "entity.project.confluence",
      type: "initiative",
      canonical_name: "Project Confluence",
      aliases: ["Confluence", "merchant_id migration", "platform unification"],
      owner: "Daniel Tan",
      confidence: 0.94,
      source_refs: ["data/overview.md", "data/weekly-review-2026-04-21.md", "data/board-update-2026-04-22.md"],
    },
    {
      id: "entity.initiative.crm_migration",
      type: "initiative",
      canonical_name: "CRM migration",
      aliases: ["CRM migration", "HubSpot migration", "Pipedrive migration"],
      owner: "Sofia Almeida",
      confidence: 0.94,
      source_refs: ["data/overview.md", "data/weekly-review-2026-04-21.md", "data/interviews/leadership/Sofia_Almeida.md"],
    },
  ];
}

function personEntityRecords(people: InterviewPerson[]): JsonRecord[] {
  const selectedNames = [
    "Maria Silva",
    "Maria Santos",
    "Aisha Yusof",
    "Aisha Mahmud",
    "Sara Wijaya",
    "Sarah Ng",
  ];
  const peopleByName = new Map(people.map((person) => [person.name, person]));

  return selectedNames.map((name) => {
    const person = peopleByName.get(name);
    if (!person) {
      throw new Error(`Missing interview metadata for ${name}`);
    }

    return {
      id: `entity.person.${slug(person.name)}`,
      type: "person",
      canonical_name: person.name,
      role: person.role,
      department: person.department,
      email: person.email,
      reports_to: reportsTo(person.name),
      distinct_from: distinctFrom(person.name),
      confidence: person.name.startsWith("Maria ") ? 0.99 : 0.98,
      source_refs: ["data/org-chart.md", person.source],
    };
  });
}

function seedFactRecords(): JsonRecord[] {
  return [
    {
      id: "fact.crm.brazil_not_started",
      subject: "entity.initiative.crm_migration",
      claim: "Brazil had not started CRM migration as of April 21, 2026; Pipedrive remained Brazil's system of record.",
      confidence: 0.97,
      source_refs: ["data/weekly-review-2026-04-21.md", "data/dashboards/sales-pipeline-2026-04-21.html", "data/interviews/leadership/Sofia_Almeida.md"],
    },
    {
      id: "fact.nps.aggregate_q1_2026",
      subject: "metric.nps",
      claim: "Aggregate Q1 2026 NPS is 47; SEA enterprise NPS is 62 and should not be treated as the company-wide number.",
      confidence: 0.98,
      source_refs: ["data/weekly-review-2026-04-21.md", "data/board-update-2026-04-22.md", "data/all-hands-2026-04-15.md"],
    },
    {
      id: "fact.confluence.current_timeline",
      subject: "entity.project.confluence",
      claim: "Current Confluence expectation is end of Q3, with realistic GA late August to mid-September / September 30, superseding the older June all-hands target.",
      confidence: 0.97,
      source_refs: ["data/weekly-review-2026-04-21.md", "data/board-update-2026-04-22.md", "data/all-hands-2026-04-15.md"],
    },
    {
      id: "fact.brazil_pipeline.quality",
      subject: "metric.brazil_pipeline_coverage",
      claim: "Brazil pipeline coverage should be treated directionally because Pipedrive records have known duplicates and cleanup was still underway.",
      confidence: 0.94,
      source_refs: ["data/dashboards/sales-pipeline-2026-04-21.html", "data/interviews/sales/joao_pereira.md", "data/weekly-review-2026-04-21.md"],
    },
  ];
}

function seedCausalRecords(): JsonRecord[] {
  return [
    {
      id: "chain.tap_brazil_underperformance",
      subject: "entity.product.tap",
      claim: "Tap underperformance in Brazil combines weak attach rate, SMB upsell/product adoption issues, Tap + Loyalty reconciliation trust problems, and delayed backend fixes tied to schema migration work.",
      confidence: 0.93,
      source_refs: ["data/weekly-review-2026-04-21.md", "data/interviews/sales/joao_pereira.md", "data/interviews/engineering/Ahmad_Rashid.md", "data/interviews/sales/maria-silva.md"],
    },
    {
      id: "chain.acai_express_issue",
      subject: "customer.acai_express",
      claim: "Açaí Express escalation is primarily a Tap + Loyalty / Loyalty reconciliation issue rooted in legacy Brazil merchant references; Confluence matters because merchant_id migration controls durable fix timing.",
      confidence: 0.94,
      source_refs: ["data/email/customer-acai-express-thread.md", "data/chat/eng-random-april.md"],
    },
    {
      id: "chain.cosmos_hotels_loss",
      subject: "customer.cosmos_hotels",
      claim: "Cosmos Hotels was lost because multi-property reporting was missing; pricing was not the issue. Confluence priorities prevented a firm product commitment, so the workaround did not satisfy the customer.",
      chain_steps: [
        "pricing was explicitly not the issue",
        "Cosmos needed consolidated multi-property reporting across 47 properties",
        "the proposed export workaround was not acceptable to the customer",
        "the product team could not commit to the reporting fix because Confluence priorities constrained roadmap capacity",
        "Cosmos chose a competitor at a similar price point",
      ],
      confidence: 0.96,
      source_refs: ["data/email/cosmos-hotels-debrief.md", "data/dashboards/april-2026-kpi-dashboard.html", "data/board-update-2026-04-22.md"],
    },
    {
      id: "chain.brazil_cs_capacity",
      subject: "team.brazil_customer_success",
      claim: "Brazil CS capacity problems stem from CSM attrition/backfill gaps, higher case volume, SMB support expectations, and Tap/Loyalty reconciliation pressure. Marco Bianchi owns CS overall; Maria Santos owns Brazil CS.",
      confidence: 0.94,
      source_refs: ["data/interviews/leadership/Marco_Bianchi.md", "data/interviews/customer_success/Maria_Santos.md", "data/weekly-review-2026-04-21.md"],
    },
  ];
}

async function readInterviewPeople() {
  const files = await listFiles(path.join(process.cwd(), "data", "interviews"));
  const people: InterviewPerson[] = [];
  for (const absolute of files.filter((file) => file.endsWith(".md"))) {
    const content = await readFile(absolute, "utf8");
    const person = {
      name: requiredMeta(content, "Name", absolute),
      role: requiredMeta(content, "Role", absolute),
      department: requiredMeta(content, "Department", absolute),
      email: requiredMeta(content, "Email", absolute),
      source: path.relative(process.cwd(), absolute),
    };
    people.push(person);
  }
  return people;
}

async function listFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const absolute = path.join(dir, entry.name);
      return entry.isDirectory() ? listFiles(absolute) : [absolute];
    }),
  );
  return files.flat().sort();
}

function requiredMeta(content: string, field: string, source: string) {
  const match = content.match(new RegExp(`^\\s*-\\s*\\*\\*${field}:\\*\\*\\s*(.+)$`, "im"));
  if (!match?.[1]) {
    throw new Error(`Missing ${field} in ${source}`);
  }
  return match[1].trim();
}

function reportsTo(name: string) {
  return {
    "Sara Wijaya": "Daniel Tan",
    "Sarah Ng": "Priya Raman",
  }[name];
}

function distinctFrom(name: string) {
  const pairs: Record<string, string> = {
    "Maria Silva": "Maria Santos",
    "Maria Santos": "Maria Silva",
    "Aisha Yusof": "Aisha Mahmud",
    "Aisha Mahmud": "Aisha Yusof",
    "Sara Wijaya": "Sarah Ng",
    "Sarah Ng": "Sara Wijaya",
  };
  return pairs[name] ? [`entity.person.${slug(pairs[name])}`] : undefined;
}

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
}

function validateSourceRefs(records: JsonRecord[]) {
  for (const record of records) {
    for (const sourceRef of record.source_refs) {
      if (!existsSync(path.join(process.cwd(), sourceRef))) {
        throw new Error(`${record.id} references missing source ${sourceRef}`);
      }
    }
  }
}

async function writeJsonl(fileName: string, records: JsonRecord[]) {
  const content = records.map((record) => JSON.stringify(removeUndefined(record))).join("\n") + "\n";
  await writeFile(path.join(normalizedDir, fileName), content, "utf8");
}

function removeUndefined(record: JsonRecord) {
  return Object.fromEntries(Object.entries(record).filter(([, value]) => value !== undefined));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
